Initial implementation
projectsyn/component-fluentbit pull request #1
Opened 2020-09-02 14:37 UTC by simu

Initial implementation

## Checklist

- [ ] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation.

2020-09-03 14:55 UTC, srueg approved these changes

2020-09-03 15:32 UTC, corvus-ch requested changes
Looks solid.

2020-09-03 15:32 UTC, corvus-ch commented on class/defaults.yml
> +    configMapName: syn-fluentbit-config
The config map is namespaced. Prefexing it with `syn-` is redundant.

```suggestion
    configMapName: fluentbit-config
```

2020-09-03 15:32 UTC, corvus-ch commented on class/defaults.yml
> +      # If key Name (specifying the plugin) doesn't exist for an entry, the
I am questioning if those comments are at the correct location. The might be better placed in the documentation. I tend to wards the later.

2020-09-03 15:32 UTC, corvus-ch commented on docs/modules/ROOT/pages/references/parameters.adoc
> +      Gelf_Short_Message_Key: log
Please add a second (and maybe third) output to showcase the handling of section/name.

2020-09-03 16:34 UTC, simu commented on class/defaults.yml
> +      # If key Name (specifying the plugin) doesn't exist for an entry, the
Already part of the documentation as well.

2020-09-03 16:34 UTC, simu commented on class/defaults.yml
> +    configMapName: syn-fluentbit-config
I added the `syn-` prefix to make it clearer which configmap contains the Project Syn-managed configuration, since the helm chart also generates a configmap, which is named `fluent-bit` with the current implementation.

2020-09-03 16:34 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +      Gelf_Short_Message_Key: log
I'm trying to figure out the best way to illustrate the section/name handling, do you think one complex example or multiple simpler examples would be better?

2020-09-04 12:09 UTC, corvus-ch approved these changes

2020-09-04 12:10 UTC, merged